name: auto-publish-lean-cloud
on:
  push:
    branches: [ main ]
jobs:
  go-publish:
    runs-on: ubuntu-latest
    environment: test
    env:
      publish_url: ${{ vars.LEANCLOUD_PUBLISH }}
    steps:
      - name: 冲鸭
        run: curl ${{publish_url}}