name: auto-publish-lean-cloud
on:
  push:
    branches: [ main ]
jobs:
  go-publish:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: 冲鸭
        run: curl -X POST ${{ secrets.LEANCLOUD_PUBLISH }} 